DROP TABLE IF EXISTS MAIL;
CREATE TABLE MAIL (
  ID_MAIL smallint NOT NULL AUTO_INCREMENT,
  SENDER varchar(256) NOT NULL,
  RECIPIENT varchar(256) NOT NULL,
  BCC_RECIPIENT varchar(256),
  SUBJECT varchar(1024),
  BODY TEXT,
  DATE_INSERT datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID_MAIL)
);

